# Generated by Django 4.2.7 on 2023-12-02 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(max_length=128, verbose_name="Address Line 1"),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "town_or_city",
                    models.CharField(max_length=64, verbose_name="Town/City"),
                ),
                ("county", models.CharField(max_length=64, verbose_name="County")),
                ("postcode", models.CharField(max_length=10, verbose_name="Postcode")),
                (
                    "country",
                    models.CharField(
                        default="United Kingdom", max_length=50, verbose_name="Country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=128)),
                ("last_name", models.CharField(blank=True, max_length=128)),
                ("stage_name", models.CharField(blank=True, max_length=128)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "facebook_link",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("rating", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("questions_responses", models.JSONField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="NewUserApp.artistprofile",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistAdditionalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("experience_years", models.IntegerField(default=0)),
                ("awards", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("audio_video_samples", models.JSONField(blank=True, null=True)),
                ("photo_gallery", models.JSONField(blank=True, null=True)),
                ("availability_schedule", models.JSONField(blank=True, null=True)),
                ("preferred_venues", models.TextField(blank=True)),
                ("travel_willingness", models.BooleanField(default=False)),
                ("equipment_needs", models.TextField(blank=True)),
                ("technical_rider", models.TextField(blank=True)),
                ("rate_information", models.TextField(blank=True)),
                ("payment_preferences", models.TextField(blank=True)),
                ("covid_vaccination_status", models.BooleanField(default=False)),
                ("dietary_preferences", models.TextField(blank=True)),
                ("insurance_details", models.TextField(blank=True)),
                ("contractual_preferences", models.TextField(blank=True)),
                ("languages_spoken", models.CharField(blank=True, max_length=256)),
                ("personal_interests", models.TextField(blank=True)),
                (
                    "artist_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="NewUserApp.artistaddress",
                    ),
                ),
                (
                    "artist_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_details",
                        to="NewUserApp.artistprofile",
                    ),
                ),
                ("genres", models.ManyToManyField(to="NewUserApp.genre")),
            ],
        ),
    ]
