# Generated by Django 4.2.7 on 2023-12-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NewUserApp", "0002_artistprofile_email"),
    ]

    operations = [
        migrations.DeleteModel(name="ArtistAdditionalDetails",),
    ]
