# Generated by Django 4.2.7 on 2023-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProfilesApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="state_province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
