# Generated by Django 4.2.7 on 2023-11-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ProfilesApp",
            "0002_profile_city_profile_country_profile_postal_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(name="profile", options={},),
        migrations.RenameField(
            model_name="profile", old_name="city", new_name="genre",
        ),
        migrations.RenameField(
            model_name="profile", old_name="country", new_name="location",
        ),
        migrations.RemoveField(model_name="profile", name="id_document",),
        migrations.RemoveField(model_name="profile", name="is_musician",),
        migrations.RemoveField(model_name="profile", name="is_venue_manager",),
        migrations.RemoveField(model_name="profile", name="postal_code",),
        migrations.RemoveField(model_name="profile", name="profile_picture",),
        migrations.RemoveField(model_name="profile", name="state_province",),
        migrations.RemoveField(model_name="profile", name="street_address",),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
